INCLUDE ffl/tst.fs

2 BASE !
00111100 CONSTANT RANKMASK
00000011 CONSTANT SUITMASK
00111111 CONSTANT RANKSUITMASK
11000000 CONSTANT GROUPCOUNTMASK
11111100 CONSTANT CARDCOMPAREMASK
DECIMAL

CREATE GROUPCOUNT 14 ALLOT

: ERASEGROUPCOUNT
    GROUPCOUNT 14 ERASE ;

: GROUPCOUNT++ ( n -- )
    GROUPCOUNT + DUP C@ 1+ SWAP C! ;

: GROUPCOUNT@ ( n -- c )
    GROUPCOUNT + C@ ;

: 5DUP ( a,b,c,d,e -- a,b,c,d,e,a,b,c,d,e )
    5 0 DO 4 PICK LOOP ;

: RANK ( card -- rank )
    RANKMASK AND 2 RSHIFT ;

: SUIT ( card -- suit )
    SUITMASK AND ;

: GROUPSIZE ( card -- n )
    6 RSHIFT 1+ ;

: <GROUPCOUNT! ( card,gc -- card' )
    1- 6 LSHIFT SWAP RANKSUITMASK AND OR ;

: CARDCOMPARE ( card,card -- -x|0|+x )
    SWAP CARDCOMPAREMASK AND
    SWAP CARDCOMPAREMASK AND
    - ;

: 2SORT ( card,card -- card,card )
    2DUP CARDCOMPARE 0 < IF SWAP THEN ;

: 3SORT ( card,card,card -- card,card,card )
    2SORT >R 2SORT R> 2SORT ;

: 4SORT ( card,card,card,card -- card,card,card,card )
    3SORT >R 3SORT R> 3SORT ;

: 5SORT ( a,d,b,c,e -- e,d,c,b,a )
    4SORT >R 4SORT R> 4SORT ;

: 5DUP ( a,b,c,d,e -- a,b,c,d,e,a,b,c,d,e )
    5 0 DO 4 PICK LOOP ;

: COUNTGROUPS ( a,b,c,d,e -- )
    ERASEGROUPCOUNT
    5 0 DO RANK GROUPCOUNT++ LOOP ;

: <GROUPCOUNTS! ( a,b,c,d,e -- )
    5 0 DO 4 ROLL DUP RANK GROUPCOUNT@ <GROUPCOUNT! LOOP ;

0 CONSTANT HEARTS
1 CONSTANT SPADES
2 CONSTANT DIAMONDS
3 CONSTANT CLUBS

10 CONSTANT TEN
11 CONSTANT JACK
12 CONSTANT QUEEN
13 CONSTANT KING
14 CONSTANT ACE

: CARD ( r,s -- card )
    SWAP 2 LSHIFT OR ;

1 HEARTS CARD CONSTANT 1H 2 HEARTS CARD CONSTANT 2H 3 HEARTS CARD CONSTANT 3H 4 HEARTS CARD CONSTANT 4H 5 HEARTS CARD CONSTANT 5H 6 HEARTS CARD CONSTANT 6H 7 HEARTS CARD CONSTANT 7H 8 HEARTS CARD CONSTANT 8H 9 HEARTS CARD CONSTANT 9H TEN HEARTS CARD CONSTANT TH JACK HEARTS CARD CONSTANT JH QUEEN HEARTS CARD CONSTANT QH KING HEARTS CARD CONSTANT KH ACE HEARTS CARD CONSTANT AH
1 SPADES CARD CONSTANT 1S 2 SPADES CARD CONSTANT 2S 3 SPADES CARD CONSTANT 3S 4 SPADES CARD CONSTANT 4S 5 SPADES CARD CONSTANT 5S 6 SPADES CARD CONSTANT 6S 7 SPADES CARD CONSTANT 7S 8 SPADES CARD CONSTANT 8S 9 SPADES CARD CONSTANT 9S TEN SPADES CARD CONSTANT TS JACK SPADES CARD CONSTANT JS QUEEN SPADES CARD CONSTANT QS KING SPADES CARD CONSTANT KS ACE SPADES CARD CONSTANT AS
1 DIAMONDS CARD CONSTANT 1D 2 DIAMONDS CARD CONSTANT 2D 3 DIAMONDS CARD CONSTANT 3D 4 DIAMONDS CARD CONSTANT 4D 5 DIAMONDS CARD CONSTANT 5D 6 DIAMONDS CARD CONSTANT 6D 7 DIAMONDS CARD CONSTANT 7D 8 DIAMONDS CARD CONSTANT 8D 9 DIAMONDS CARD CONSTANT 9D TEN DIAMONDS CARD CONSTANT TD JACK DIAMONDS CARD CONSTANT JD QUEEN DIAMONDS CARD CONSTANT QD KING DIAMONDS CARD CONSTANT KD ACE DIAMONDS CARD CONSTANT AD
1 CLUBS CARD CONSTANT 1C 2 CLUBS CARD CONSTANT 2C 3 CLUBS CARD CONSTANT 3C 4 CLUBS CARD CONSTANT 4C 5 CLUBS CARD CONSTANT 5C 6 CLUBS CARD CONSTANT 6C 7 CLUBS CARD CONSTANT 7C 8 CLUBS CARD CONSTANT 8C 9 CLUBS CARD CONSTANT 9C TEN CLUBS CARD CONSTANT TC JACK CLUBS CARD CONSTANT JC QUEEN CLUBS CARD CONSTANT QC KING CLUBS CARD CONSTANT KC ACE CLUBS CARD CONSTANT AC

CREATE RANKS
CHAR 0 C, CHAR 1 C, CHAR 2 C, CHAR 3 C, CHAR 4 C, CHAR 5 C, CHAR 6 C, CHAR 7 C, CHAR 8 C, CHAR 9 C, CHAR T C, CHAR J C, CHAR Q C, CHAR K C, CHAR A C,

CREATE SUITS
CHAR H C, CHAR S C, CHAR D C, CHAR C C,

: .GROUPSIZE ( n -- )
    [CHAR] ( EMIT 0 .R [CHAR] ) EMIT ;

: .RANK ( r -- )
    RANKS + C@ EMIT ;

: .SUIT ( s -- )
    SUITS + C@ EMIT ;

: .CARD ( card -- )
    DUP RANK .RANK
    SUIT .SUIT
    SPACE ;

: .GSCARD ( card -- )
    DUP GROUPSIZE .GROUPSIZE
    .CARD ;

: HAND ( a,e,c,d,b -- e,c,d,b,a sorted by group size then rank )
    5DUP COUNTGROUPS
    <GROUPCOUNTS!
    5SORT ;

: 5REVERSE ( a,b,c,d,e -- e,b,c,d,a )
    4 ROLL >R        \ b,c,d,e [a]
    SWAP             \ b,c,e,d
    2SWAP            \ e,d,b,c
    SWAP R> ;        \ e,d,c,b,a

: .HAND
    5REVERSE 5 0 DO .CARD LOOP ;

: TESTSORTCARDS
    ." CARDS ARE SORTED BY GROUP SIZE AND RANK DESC." CR
    QS 3C QD 3D 3S HAND .HAND CR
    AC 5D KC 5H 4S HAND .HAND CR
    2S KC 2C 2H 2D HAND .HAND CR
;

TESTSORTCARDS
CR


